version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root@1234
    ports:
      - "27017:27017"
    volumes:
      - ./Databases/mongo_data:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: Talkative       # Name of the database
#      MYSQL_USER: root               # Custom username
#      MYSQL_PASSWORD: root@1234       # Custom user password
#      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    volumes:
      - ./Databases/mysql_data:/var/lib/mysql  # Persist MySQL data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./Redis/Cache:/data
#    environment:
#      - REDIS_PASSWORD="root@1234"  # Define a password here if needed
#    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Use environment variable for password
    command: ["redis-server"]