version: '3.8'
services:

  mongodb:
    image: mongo:latest
    container_name: mongo_db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root@1234
#      - MONGO_INITDB_DATABASE= {MONGO_AUTH_DB}
    ports:
      - "${MONGODB_AUTH_PORT:-27017}:27017"
    volumes:
      - MongoDb_Jwt_data:/data/db

  mysql_Auth:
    image: mysql:latest
    container_name: mysql_Auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_AUTH_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_AUTH_DATABASE}       # Name of the database
#      MYSQL_USER: root               # Custom username
#      MYSQL_PASSWORD: root@1234       # Custom user password
#      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "${MYSQL_AUTH_PORT:-3306}:3306"  # Expose MySQL on port 3306
    volumes:
      - MySQl_Auth_data:/var/lib/mysql  # Persist MySQL data
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_AUTH_PORT:-6379}:6379"
    volumes:
      - Redis_Auth_data:/data
    #    environment:
    #      - REDIS_PASSWORD="root@1234"  # Define a password here if needed
    #    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Use environment variable for password
    command: [ "redis-server" ]



volumes:
  Redis_Auth_data:
  MySQl_Auth_data:
  MongoDb_Jwt_data:


