apiVersion: apps/v1
kind: Deployment
metadata:
  name: individual-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: individual-service
  template:
    metadata:
      labels:
        app: individual-service
    spec:
      containers:
        - name: individual-service
          image: individual-service:latest  # Use your image name
          ports:
            - containerPort: 8086
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: individual-service
spec:
  type: NodePort
  selector:
    app: individual-service
  ports:
    - protocol: TCP
      port: 80
      nodePort: 8086
      targetPort: 8086  # Match your container port
