CREATE TABLE IF NOT EXISTS SessionTable (
    SessionID BIGSERIAL PRIMARY KEY,
    RoomID BIGINT NOT NULL,
    UserId BIGINT NOT NULL,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT FALSE
);
