apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: connection-service
  template:
    metadata:
      labels:
        app: connection-service
    spec:
      containers:
        - name: connection-service
          image: connection-service:latest  # Use your image name
          ports:
            - containerPort: 8085
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: connection-service
spec:
  type: NodePort
  selector:
    app: connection-service
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30003
      targetPort: 8085  # Match your container port
