apiVersion: apps/v1
kind: Deployment
metadata:
  name: individual-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: individual-service
  template:
    metadata:
      labels:
        app: individual-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node-name  # Specify the name of the node
      containers:
        - name: individual-service
          image: individual-service:latest
          ports:
            - containerPort: 8080
