apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: individual-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: individual-service  # Name of the connection service deployment
  minReplicas: 1  # Minimum number of pods to run
  maxReplicas: 5  # Maximum number of pods to scale to
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Scale if CPU usage goes over 50%
